### ISSUE TITLE
Expected ResultSet exhaustion

### ISSUE THREAD

**Issue by Bruschkov** [snowplow-incubator/igluctl#101]
Hi,
we recently tried to migrate our old Redshift Tables to the new format, so we can leverage table autocreation in the rdb-loader. Unfortunately, `igluctl rdbms table-check` and `igluctl rdbms table-migrate` crash with the same following error:
```
doobie.util.invariant$UnexpectedContinuation$: Expected ResultSet exhaustion, but more rows were available.
        at doobie.util.invariant$UnexpectedContinuation$.<clinit>(invariant.scala)    
        at doobie.hi.resultset$.$anonfun$getOption$1(resultset.scala:218)                                                                                                            
        at cats.free.Free.step(Free.scala:56)                                                                                                                                        
        at cats.free.Free.$anonfun$foldMap$1(Free.scala:143)             
        at cats.data.KleisliFlatMap.$anonfun$tailRecM$2(Kleisli.scala:640)
        at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:16)
        at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:15)               
        at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:167)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
        at blockOn$extension @ doobie.util.transactor$Transactor$fromDriverManager$.$anonfun$create$1(transactor.scala:358)
        at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:167)          
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
        at blockOn$extension @ doobie.util.transactor$Transactor$fromDriverManager$.$anonfun$create$1(transactor.scala:358)
        at $anonfun$tailRecM$1 @ doobie.util.transactor$Transactor$$anon$4.$anonfun$apply$4(transactor.scala:167)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
        at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:750)
```

command: `igluctl rdbms table-check --resolver iglu_resolver.json --schema "iglu:some/schema/jsonschema/1-0-0" --host some-host --username user --password pwd --dbname events --dbschema atomic`

igluctl version: 0.8.1

**Comment by chuwy** [comment]
Hi @Bruschkov! I don't think it's a bug, but error message certainly must be clearer.

I think the reason might be that you're checking the `events` table and it's a special table and the commands are not applicable to it. And it's not affected by any auto-migration logic.

In other words, run these commands against all other tables, except `events`.

**Comment by Bruschkov** [comment]
Hey, thanks for your quick reply!

So the parameter `dbname` does in fact not refer to name of the database?

I think in Redshift the hierarchy is database -> schema -> table

**Comment by chuwy** [comment]
I can tell for sure that it happens when igluctl performs this query:

```sql
SELECT oid, obj_description(oid) AS comment FROM pg_class WHERE relname = $tableName
```

I also think that this happens because nothing there specifies a DB schema. In other words, if you have a table with the same name in several schemas the above query will return an iinvalid result.

I don't think we can release a bugfix in foreseable future. Do you think you can workaround it somehow?

**Comment by Bruschkov** [comment]
Hey, thanks for finding the bug so quickly. Do you think adding the schema to the query would fix the issue? Then I can do it myself and build the tool locally from source.

This query should yield the correct result by using the schema defined in the function Parameter (which is the one set in the command line parameter?)

```Scala
def getComment(tableName: String, tableSchema: String)(implicit F: Bracket[F, Throwable]) =
    fr"SELECT C.oid, obj_description(C.oid) AS comment, trim(nspname) AS schemaname FROM pg_class C
             LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
             WHERE C.relname = $tableName
            AND schemaname = $tableSchema"
      .query[Storage.Comment].option.transact(xa)
```

**Comment by Bruschkov** [comment]
Alright, thanks.

By the way, we have already done that, but have gotten no reply so far... 
https://discourse.snowplowanalytics.com/t/rdb-loader-sql-null-read-at-column-1-jdbc-type-char/6501
